# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af153ad9de62558664d5d3be5022f435"
name = "Socoba Neon Prime DRaft Order"
application_url = "https://socoba-draft-order-neon-prime.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders_create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_draft_orders,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[app_proxy]
url = "https://socoba-draft-order-neon-prime.onrender.com"
subpath = "draft-order"
prefix = "apps"

[auth]
redirect_urls = [
  "https://socoba-draft-order-neon-prime.onrender.com/auth/callback",
  "https://socoba-draft-order-neon-prime.onrender.com/auth/shopify/callback",
  "https://socoba-draft-order-neon-prime.onrender.com/api/auth/callback",
  "https://socoba-draft-order-neon-prime.onrender.com/login"
]
